# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: klocwork
on:
  schedule:
    - cron: '0 0 * * SUN' # Runs at midnight every Sunday
  # Manually run this workflow on any specified branch.
  workflow_dispatch:

env:
  KLOCWORK_DIR: ~/kwbuildtools/bin/
  PROJECT_NAME: HEBench-APIBridge_github-ci
  KLOCWORK_SERVER: $KLOCWORK_SERVER_GLADE

jobs:
  klocwork:
    name: klocwork scan
    runs-on: icx
    steps:
      - name: Clone Repository (Latest on development)
        uses: actions/checkout@v2
        if: github.event.ref == ''
        with:
          ref: development
      - name: Clone Repository (Manual Selection)
        uses: actions/checkout@v2
        if: github.event.ref != ''
        with:
          ref: ${{ github.event.ref }}

      - name: Setup
        run: |
          git branch --show-current 

          mkdir build
          cmake -S . -B build
          echo "${{ env.KLOCWORK_DIR }}" >> $GITHUB_PATH
          cat ~/klocwork-server.txt >> $GITHUB_ENV

      - name: Build Klocwork Project
        run: |
          kwinject make -j
          # kwbuildproject may have non-zero exit
          # Build errors will be logged and accessible on server
          kwbuildproject --url ${{ env.KLOCWORK_SERVER }}/${{ env.PROJECT_NAME }} kwinject.out --tables-directory tables
        continue-on-error: true
        working-directory: ./build

      - name: Upload Klocwork Results
        run: |
          # Add checkerset (v21.2 is currently unavailable)
          kwadmin --url ${{ env.KLOCWORK_SERVER }} import-config ${{ env.PROJECT_NAME }} ~/KW21-1_Checker_Set.pconf;
          kwadmin --url ${{ env.KLOCWORK_SERVER }} load ${{ env.PROJECT_NAME }} tables
        working-directory: ./build
